### ISSUE TITLE
'std' error

### ISSUE THREAD

**Issue by NeMeJP** [metabotics-ai/MetaLidar#14]
When building from source after adding MetaLidar, the plugin pulls multiple errors mainly from 'std' calls.
Files : LidarBaseActor.h and VelodyneLidarActor.cpp

![image](https://github.com/metabotics-ai/MetaLidar/assets/133895904/b26480f2-1308-4e1b-a378-ade07a4e7558)
![Capture](https://github.com/metabotics-ai/MetaLidar/assets/133895904/0dfc499d-972a-4b49-8f12-376af4ba1b90)
![Capture2](https://github.com/metabotics-ai/MetaLidar/assets/133895904/f4b11bdc-3dfb-412c-9277-11b7356184fe)
![Capture3](https://github.com/metabotics-ai/MetaLidar/assets/133895904/96f82c56-4a87-4f8d-a611-04c2e473b596)

I'm using the latest UE 5 source from the UE repo.

**Comment by james-yoo** [comment]
@NeMeJP
Would you mind testing with the UE5  stable release(not source build) while I work on the error? You can get the latest release (v5.2.1) from here:
https://www.unrealengine.com/en/linux

**Comment by metabotics** [comment]
Issue resolved by 7ffa10cdaccca2e2ab3799530201bfd1fd7728ba
