### ISSUE TITLE
Is it possible to view laser scan preview in the viewport? 

### ISSUE THREAD

**Issue by wakasturner** [metabotics-ai/MetaLidar#18]
Hi,

First of all, great work! I have been looking for an unreal simulation for Velodyne LiDARs. One thing I want to ask is: is there a way to turn on the laser scan preview in the viewport? I have seen that it is possible and the AirSim plugin does something similar.

Regards

**Comment by metabotics** [comment]
Hi, @wakasu 
Unfortunately, the scan preview in the viewport is not implemented due to performance issues. For visualization, it is recommended to use a legacy viewer such as [LidarView](https://gitlab.kitware.com/LidarView/lidarview/-/releases).

**Comment by wakasturner** [comment]
Hey @metabotics 
Thank you for the prompt reply. The project I am currently working on requires the scan to be visible in the viewport as the lidar is moving in the environment. I understand that there might be a performance hit, but could you please guide me on where I should start if I want to implement this as an optional feature for the project?

Regards,

**Comment by metabotics** [comment]
Hi @wakasu,
You can get [HitResult](https://docs.unrealengine.com/5.3/en-US/API/Runtime/Engine/Engine/FHitResult/) in 'VelodyneBaseComponent.cpp'.
https://github.com/metabotics-ai/MetaLidar/blob/12ae3a359fcfb2a3246dc1dc3dbfe7002f7edce4/Source/MetaLidar/Private/Velodyne/VelodyneBaseComponent.cpp#L274
FHitResult structure contains information about one hit of a trace, such as point of impact and surface normal at that point. By using this structure with [DrawPoint](https://docs.unrealengine.com/5.3/en-US/API/Runtime/InteractiveToolsFramework/FToolDataVisualizer/DrawPoint/3/) function, you will be able to draw scan point at runtime in the viewport.

cc @james-yoo

**Comment by wakasturner** [comment]
@metabotics 
Thanks for the pointers.🙌

**Comment by S1ink** [comment]
@wakasu I used [this project](https://github.com/ValentinKraft/UE4_GPUPointCloudRenderer) to successfully view point clouds in UE5 (a gpu shader so performance was not a problem). I ended up modifying it significantly since it was made for UE4 and has not been updated - the project is [here](https://github.com/S1ink/UE5-LidarSim) (renderer is under Plugins/GPUPointCloudRenderer). Basically just add the component to a blueprint and then call the respective render function.

**Comment by wakasturner** [comment]
Hey @S1ink,
Thank you for sharing your work. I have experience in Gazebo and Blender for train models, but this is my first time working in Unreal. Your code will be a lot of help. Thanks. 🙌

**Comment by S1ink** [comment]
@wakasu You are very welcome 👍

**Comment by wakasturner** [comment]
Hey @metabotics 
One more question if you don't mind, 
What's the reason for Linux to be the only supported system? Will this not work in a Unreal Project on windows?

**Comment by metabotics** [comment]
Hi, @wakasu
Your question is off-topic for the current issue, so please open a new one.
