### ISSUE TITLE
MetaLidar: Windows Compatibility?

### ISSUE THREAD

**Issue by wakasturner** [metabotics-ai/MetaLidar#20]
Why is Linux the only supported system for developing Unreal Engine projects? 
Can I not use Unreal Engine on a Windows platform?

**Comment by james-yoo** [comment]
Hi, @wakasu 
I did not dig into this issue, I remember not being able to get an accurate timestamp when testing on Windows. This plugin requires a high-resolution timestamp to create an accurate data packet.

**Comment by wakasturner** [comment]
Apologies for the delayed response.

My objective is to have a simulation environment running on Windows. However, for the time being, I will be setting up a Linux development environment. I will also look into the accuracy of timestamps when working on Windows.

Cheers.
