### ISSUE TITLE
Loop Back Works... kinda

### ISSUE THREAD

**Issue by Interaze** [metabotics-ai/MetaLidar#21]
I was able to make the loopback work when I set the velodyne plugin to have the sensor ip be my private IP, then set the destination ip to 127.0.0.1. With that, you can bind a docker container to 127.0.0.1 with udp to listen to the port. The hardest part is configuring (if you're using a velodyne ros driver) the ip address to listen to... it will not be the same as either ip address. For me it was 172.18.0.1 and I only found out by a log another container I had posting it, and throwing a hail mary. I didn't need anything fancy though like network_mode host. Hopefully this can help other people dealing with this.

Awesome work,
Cheers

**Comment by james-yoo** [comment]
Hi, @Interaze 
Thanks for sharing the loopback connection! I will try it.
